# Site settings
title: 
header-img: img/home-bg.png
email: lap5151@gmail.com
copyright_name: lap5151
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lap5151
learn_profile: lap5151
email_username: lap5151@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
